<?xml version="1.0" encoding="utf-8"?><Database Name="PHOBIC" Class="PouchDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=iolSERVER2023;Initial Catalog=PHOBIC;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PHOBICConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LENS_MASTER" Member="LENS_MASTERs">
    <Type Name="LENS_MASTER">
      <Column Name="Header_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Detail_ID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Brand_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reference_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GS_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Power" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Optic" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Length" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Lot_Unit" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="A_Constant" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Type_GS_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tot_Exp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_By" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_By" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="price" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Product_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicenceNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name_address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Storage_Temp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sterilize_type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.POUCH_LABEL" Member="POUCH_LABELs">
    <Type Name="POUCH_LABEL">
      <Column Name="Brand_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reference_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GS_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Power" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Optic" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Length" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Lot_Unit" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="A_Constant" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Type_GS_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="St_SrNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="St_EnNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lot_Prefix" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lot_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lot_SrNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mfd_Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mfd_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Exp_Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Exp_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sterilization" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sterilization_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sample_Taken" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type_Sample" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BPL_Taken" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPL_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Box_Packing" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dc_Packing_List" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DCL_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dc_Packing" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dc_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Plant" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Created_By" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_By" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sterilization_After" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sterilization_No_After" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sterilization_Reject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Qty_1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Box_Reject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Box_Reject_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Box_Reject_By" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Sterilization_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sterilization_By" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Box_By" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Box_Date" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Print_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Packing_Model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ord_Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="numoflens" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="numofbigbox" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="numofsbinbb" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="scan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Small_box" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Big_box" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Numofsbox" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Btc_No" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="price" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Sterility_Comp_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sales_Ord_No" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sterility_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Injector_Ref" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Injector_batch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_Power" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Cylsize" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="rotlex_type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Label" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RefLot" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MTS_No" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Box_No" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Dc_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PouchPrint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PowerPrint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Export_Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Inward_No" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Inward_No1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Inward_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Box_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Boxtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PouchStation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Station" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PouchBTWLabelName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tray_Label_Gen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tray_No" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Udi_code" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Injector_Lot" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rack_Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pouchRepack_staus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPL_Collection_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bpl_cancel_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPL_Collected_by" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Repk_Scanned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Areation_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Areation_scan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sterilization_scan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pouch_Order_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pouch_Order_Country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Areation_Scan_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sterile_to_Areation_Move_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sterile_to_Areation_Move_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BoxBTWLabelName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShrinkWarp_Rejection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShrinkWarp_Rejection_Move_No" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PouchPack_to_Sterile_Move_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PouchPack_to_Sterile_Move_No" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tray_Allot_No" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lens_Reserved_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reserved_Id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BI_Start_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BI_End_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>