#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PHOBIC")]
public partial class PouchDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public PouchDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PHOBICConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PouchDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PouchDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PouchDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PouchDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<LENS_MASTER> LENS_MASTERs
	{
		get
		{
			return this.GetTable<LENS_MASTER>();
		}
	}
	
	public System.Data.Linq.Table<POUCH_LABEL> POUCH_LABELs
	{
		get
		{
			return this.GetTable<POUCH_LABEL>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LENS_MASTER")]
public partial class LENS_MASTER
{
	
	private System.Nullable<int> _Header_ID;
	
	private string _Detail_ID;
	
	private string _Brand_Name;
	
	private string _Model_Name;
	
	private string _Reference_Name;
	
	private string _GS_Code;
	
	private System.Nullable<decimal> _Power;
	
	private System.Nullable<decimal> _Optic;
	
	private System.Nullable<decimal> _Length;
	
	private string _Lot_Unit;
	
	private System.Nullable<decimal> _A_Constant;
	
	private string _Type_GS_Code;
	
	private System.Nullable<int> _Tot_Exp;
	
	private string _Created_By;
	
	private System.Nullable<System.DateTime> _Created_Date;
	
	private string _Modified_By;
	
	private System.Nullable<System.DateTime> _Modified_Date;
	
	private string _price;
	
	private string _Product_code;
	
	private string _LicenceNo;
	
	private string _Name_address;
	
	private string _Storage_Temp;
	
	private string _Sterilize_type;
	
	private string _Type;
	
	public LENS_MASTER()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Header_ID", DbType="Int")]
	public System.Nullable<int> Header_ID
	{
		get
		{
			return this._Header_ID;
		}
		set
		{
			if ((this._Header_ID != value))
			{
				this._Header_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail_ID", DbType="VarChar(10)")]
	public string Detail_ID
	{
		get
		{
			return this._Detail_ID;
		}
		set
		{
			if ((this._Detail_ID != value))
			{
				this._Detail_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Name", DbType="NVarChar(50)")]
	public string Brand_Name
	{
		get
		{
			return this._Brand_Name;
		}
		set
		{
			if ((this._Brand_Name != value))
			{
				this._Brand_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model_Name", DbType="NVarChar(50)")]
	public string Model_Name
	{
		get
		{
			return this._Model_Name;
		}
		set
		{
			if ((this._Model_Name != value))
			{
				this._Model_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference_Name", DbType="NVarChar(50)")]
	public string Reference_Name
	{
		get
		{
			return this._Reference_Name;
		}
		set
		{
			if ((this._Reference_Name != value))
			{
				this._Reference_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GS_Code", DbType="NVarChar(50)")]
	public string GS_Code
	{
		get
		{
			return this._GS_Code;
		}
		set
		{
			if ((this._GS_Code != value))
			{
				this._GS_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Power", DbType="Money")]
	public System.Nullable<decimal> Power
	{
		get
		{
			return this._Power;
		}
		set
		{
			if ((this._Power != value))
			{
				this._Power = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Optic", DbType="Money")]
	public System.Nullable<decimal> Optic
	{
		get
		{
			return this._Optic;
		}
		set
		{
			if ((this._Optic != value))
			{
				this._Optic = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Money")]
	public System.Nullable<decimal> Length
	{
		get
		{
			return this._Length;
		}
		set
		{
			if ((this._Length != value))
			{
				this._Length = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lot_Unit", DbType="VarChar(10)")]
	public string Lot_Unit
	{
		get
		{
			return this._Lot_Unit;
		}
		set
		{
			if ((this._Lot_Unit != value))
			{
				this._Lot_Unit = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Constant", DbType="Money")]
	public System.Nullable<decimal> A_Constant
	{
		get
		{
			return this._A_Constant;
		}
		set
		{
			if ((this._A_Constant != value))
			{
				this._A_Constant = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_GS_Code", DbType="NVarChar(50)")]
	public string Type_GS_Code
	{
		get
		{
			return this._Type_GS_Code;
		}
		set
		{
			if ((this._Type_GS_Code != value))
			{
				this._Type_GS_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Exp", DbType="Int")]
	public System.Nullable<int> Tot_Exp
	{
		get
		{
			return this._Tot_Exp;
		}
		set
		{
			if ((this._Tot_Exp != value))
			{
				this._Tot_Exp = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_By", DbType="VarChar(50)")]
	public string Created_By
	{
		get
		{
			return this._Created_By;
		}
		set
		{
			if ((this._Created_By != value))
			{
				this._Created_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Created_Date
	{
		get
		{
			return this._Created_Date;
		}
		set
		{
			if ((this._Created_Date != value))
			{
				this._Created_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_By", DbType="VarChar(50)")]
	public string Modified_By
	{
		get
		{
			return this._Modified_By;
		}
		set
		{
			if ((this._Modified_By != value))
			{
				this._Modified_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Modified_Date
	{
		get
		{
			return this._Modified_Date;
		}
		set
		{
			if ((this._Modified_Date != value))
			{
				this._Modified_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="VarChar(30)")]
	public string price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_code", DbType="NVarChar(50)")]
	public string Product_code
	{
		get
		{
			return this._Product_code;
		}
		set
		{
			if ((this._Product_code != value))
			{
				this._Product_code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenceNo", DbType="VarChar(50)")]
	public string LicenceNo
	{
		get
		{
			return this._LicenceNo;
		}
		set
		{
			if ((this._LicenceNo != value))
			{
				this._LicenceNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_address", DbType="NVarChar(MAX)")]
	public string Name_address
	{
		get
		{
			return this._Name_address;
		}
		set
		{
			if ((this._Name_address != value))
			{
				this._Name_address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Storage_Temp", DbType="VarChar(50)")]
	public string Storage_Temp
	{
		get
		{
			return this._Storage_Temp;
		}
		set
		{
			if ((this._Storage_Temp != value))
			{
				this._Storage_Temp = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilize_type", DbType="VarChar(50)")]
	public string Sterilize_type
	{
		get
		{
			return this._Sterilize_type;
		}
		set
		{
			if ((this._Sterilize_type != value))
			{
				this._Sterilize_type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this._Type = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POUCH_LABEL")]
public partial class POUCH_LABEL
{
	
	private string _Brand_Name;
	
	private string _Model_Name;
	
	private string _Reference_Name;
	
	private string _GS_Code;
	
	private string _Power;
	
	private System.Nullable<decimal> _Optic;
	
	private System.Nullable<decimal> _Length;
	
	private string _Lot_Unit;
	
	private System.Nullable<decimal> _A_Constant;
	
	private string _Type_GS_Code;
	
	private System.Nullable<int> _Qty;
	
	private System.Nullable<int> _St_SrNo;
	
	private System.Nullable<int> _St_EnNo;
	
	private string _Lot_Prefix;
	
	private string _Lot_No;
	
	private string _Lot_SrNo;
	
	private System.Nullable<int> _Mfd_Month;
	
	private System.Nullable<int> _Mfd_Year;
	
	private System.Nullable<int> _Exp_Month;
	
	private System.Nullable<int> _Exp_Year;
	
	private System.Nullable<int> _Sterilization;
	
	private string _Sterilization_No;
	
	private System.Nullable<int> _Sample_Taken;
	
	private string _Type_Sample;
	
	private System.Nullable<int> _BPL_Taken;
	
	private string _BPL_NO;
	
	private System.Nullable<int> _Box_Packing;
	
	private System.Nullable<int> _Dc_Packing_List;
	
	private string _DCL_No;
	
	private System.Nullable<int> _Dc_Packing;
	
	private string _Dc_No;
	
	private string _Plant;
	
	private string _Created_By;
	
	private System.Nullable<System.DateTime> _Created_Date;
	
	private string _Modified_By;
	
	private System.Nullable<System.DateTime> _Modified_Date;
	
	private System.Nullable<int> _Sterilization_After;
	
	private string _Sterilization_No_After;
	
	private System.Nullable<int> _Sterilization_Reject;
	
	private System.Nullable<int> _Qty_1;
	
	private string _Type;
	
	private System.Nullable<int> _Box_Reject;
	
	private System.Nullable<System.DateTime> _Box_Reject_Date;
	
	private string _Box_Reject_By;
	
	private System.Nullable<System.DateTime> _Sterilization_Date;
	
	private string _Sterilization_By;
	
	private string _Box_By;
	
	private string _Box_Date;
	
	private string _Print_Name;
	
	private string _Packing_Model;
	
	private string _Ord_Country;
	
	private System.Nullable<int> _numoflens;
	
	private System.Nullable<int> _numofbigbox;
	
	private System.Nullable<int> _numofsbinbb;
	
	private System.Nullable<int> _scan;
	
	private System.Nullable<int> _Small_box;
	
	private System.Nullable<int> _Big_box;
	
	private System.Nullable<int> _Numofsbox;
	
	private string _Btc_No;
	
	private string _price;
	
	private System.Nullable<System.DateTime> _Sterility_Comp_Date;
	
	private string _Sales_Ord_No;
	
	private System.Nullable<int> _Sterility_Status;
	
	private string _Injector_Ref;
	
	private string _Injector_batch;
	
	private string _R_Power;
	
	private string _Cylsize;
	
	private string _rotlex_type;
	
	private System.Nullable<int> _Label;
	
	private string _RefLot;
	
	private string _Status;
	
	private string _MTS_No;
	
	private string _Box_No;
	
	private System.Nullable<int> _Dc_Status;
	
	private string _Product_code;
	
	private System.Nullable<int> _PouchPrint;
	
	private System.Nullable<int> _PowerPrint;
	
	private System.Nullable<int> _Export_Qty;
	
	private string _Location;
	
	private System.Nullable<int> _Inward_No;
	
	private string _Inward_No1;
	
	private System.Nullable<System.DateTime> _Inward_Date;
	
	private string _Box_Type;
	
	private System.Nullable<System.DateTime> _Boxtime;
	
	private string _PouchStation;
	
	private string _Station;
	
	private string _PouchBTWLabelName;
	
	private System.Nullable<int> _Tray_Label_Gen;
	
	private string _Tray_No;
	
	private string _Udi_code;
	
	private string _Injector_Lot;
	
	private string _Rack_Location;
	
	private System.Nullable<int> _pouchRepack_staus;
	
	private System.Nullable<int> _BPL_Collection_Status;
	
	private System.Nullable<int> _bpl_cancel_status;
	
	private string _BPL_Collected_by;
	
	private System.Nullable<int> _Repk_Scanned;
	
	private System.Nullable<int> _Areation_Status;
	
	private System.Nullable<int> _Areation_scan;
	
	private System.Nullable<int> _Sterilization_scan;
	
	private string _Pouch_Order_Type;
	
	private string _Pouch_Order_Country;
	
	private string _Areation_Scan_No;
	
	private System.Nullable<int> _Sterile_to_Areation_Move_status;
	
	private string _Sterile_to_Areation_Move_NO;
	
	private string _BoxBTWLabelName;
	
	private System.Nullable<int> _ShrinkWarp_Rejection;
	
	private string _ShrinkWarp_Rejection_Move_No;
	
	private System.Nullable<int> _PouchPack_to_Sterile_Move_status;
	
	private string _PouchPack_to_Sterile_Move_No;
	
	private string _Tray_Allot_No;
	
	private System.Nullable<int> _Lens_Reserved_status;
	
	private string _Reserved_Id;
	
	private System.Nullable<System.DateTime> _BI_Start_Date;
	
	private System.Nullable<System.DateTime> _BI_End_Date;
	
	public POUCH_LABEL()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Name", DbType="NVarChar(50)")]
	public string Brand_Name
	{
		get
		{
			return this._Brand_Name;
		}
		set
		{
			if ((this._Brand_Name != value))
			{
				this._Brand_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model_Name", DbType="NVarChar(50)")]
	public string Model_Name
	{
		get
		{
			return this._Model_Name;
		}
		set
		{
			if ((this._Model_Name != value))
			{
				this._Model_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference_Name", DbType="NVarChar(50)")]
	public string Reference_Name
	{
		get
		{
			return this._Reference_Name;
		}
		set
		{
			if ((this._Reference_Name != value))
			{
				this._Reference_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GS_Code", DbType="NVarChar(50)")]
	public string GS_Code
	{
		get
		{
			return this._GS_Code;
		}
		set
		{
			if ((this._GS_Code != value))
			{
				this._GS_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Power", DbType="VarChar(10)")]
	public string Power
	{
		get
		{
			return this._Power;
		}
		set
		{
			if ((this._Power != value))
			{
				this._Power = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Optic", DbType="Money")]
	public System.Nullable<decimal> Optic
	{
		get
		{
			return this._Optic;
		}
		set
		{
			if ((this._Optic != value))
			{
				this._Optic = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Money")]
	public System.Nullable<decimal> Length
	{
		get
		{
			return this._Length;
		}
		set
		{
			if ((this._Length != value))
			{
				this._Length = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lot_Unit", DbType="VarChar(10)")]
	public string Lot_Unit
	{
		get
		{
			return this._Lot_Unit;
		}
		set
		{
			if ((this._Lot_Unit != value))
			{
				this._Lot_Unit = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Constant", DbType="Money")]
	public System.Nullable<decimal> A_Constant
	{
		get
		{
			return this._A_Constant;
		}
		set
		{
			if ((this._A_Constant != value))
			{
				this._A_Constant = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_GS_Code", DbType="NVarChar(50)")]
	public string Type_GS_Code
	{
		get
		{
			return this._Type_GS_Code;
		}
		set
		{
			if ((this._Type_GS_Code != value))
			{
				this._Type_GS_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
	public System.Nullable<int> Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this._Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_St_SrNo", DbType="Int")]
	public System.Nullable<int> St_SrNo
	{
		get
		{
			return this._St_SrNo;
		}
		set
		{
			if ((this._St_SrNo != value))
			{
				this._St_SrNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_St_EnNo", DbType="Int")]
	public System.Nullable<int> St_EnNo
	{
		get
		{
			return this._St_EnNo;
		}
		set
		{
			if ((this._St_EnNo != value))
			{
				this._St_EnNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lot_Prefix", DbType="NVarChar(50)")]
	public string Lot_Prefix
	{
		get
		{
			return this._Lot_Prefix;
		}
		set
		{
			if ((this._Lot_Prefix != value))
			{
				this._Lot_Prefix = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lot_No", DbType="NVarChar(50)")]
	public string Lot_No
	{
		get
		{
			return this._Lot_No;
		}
		set
		{
			if ((this._Lot_No != value))
			{
				this._Lot_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lot_SrNo", DbType="NVarChar(50)")]
	public string Lot_SrNo
	{
		get
		{
			return this._Lot_SrNo;
		}
		set
		{
			if ((this._Lot_SrNo != value))
			{
				this._Lot_SrNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mfd_Month", DbType="Int")]
	public System.Nullable<int> Mfd_Month
	{
		get
		{
			return this._Mfd_Month;
		}
		set
		{
			if ((this._Mfd_Month != value))
			{
				this._Mfd_Month = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mfd_Year", DbType="Int")]
	public System.Nullable<int> Mfd_Year
	{
		get
		{
			return this._Mfd_Year;
		}
		set
		{
			if ((this._Mfd_Year != value))
			{
				this._Mfd_Year = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exp_Month", DbType="Int")]
	public System.Nullable<int> Exp_Month
	{
		get
		{
			return this._Exp_Month;
		}
		set
		{
			if ((this._Exp_Month != value))
			{
				this._Exp_Month = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exp_Year", DbType="Int")]
	public System.Nullable<int> Exp_Year
	{
		get
		{
			return this._Exp_Year;
		}
		set
		{
			if ((this._Exp_Year != value))
			{
				this._Exp_Year = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization", DbType="Int")]
	public System.Nullable<int> Sterilization
	{
		get
		{
			return this._Sterilization;
		}
		set
		{
			if ((this._Sterilization != value))
			{
				this._Sterilization = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization_No", DbType="NVarChar(50)")]
	public string Sterilization_No
	{
		get
		{
			return this._Sterilization_No;
		}
		set
		{
			if ((this._Sterilization_No != value))
			{
				this._Sterilization_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sample_Taken", DbType="Int")]
	public System.Nullable<int> Sample_Taken
	{
		get
		{
			return this._Sample_Taken;
		}
		set
		{
			if ((this._Sample_Taken != value))
			{
				this._Sample_Taken = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Sample", DbType="NVarChar(50)")]
	public string Type_Sample
	{
		get
		{
			return this._Type_Sample;
		}
		set
		{
			if ((this._Type_Sample != value))
			{
				this._Type_Sample = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPL_Taken", DbType="Int")]
	public System.Nullable<int> BPL_Taken
	{
		get
		{
			return this._BPL_Taken;
		}
		set
		{
			if ((this._BPL_Taken != value))
			{
				this._BPL_Taken = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPL_NO", DbType="NVarChar(50)")]
	public string BPL_NO
	{
		get
		{
			return this._BPL_NO;
		}
		set
		{
			if ((this._BPL_NO != value))
			{
				this._BPL_NO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_Packing", DbType="Int")]
	public System.Nullable<int> Box_Packing
	{
		get
		{
			return this._Box_Packing;
		}
		set
		{
			if ((this._Box_Packing != value))
			{
				this._Box_Packing = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dc_Packing_List", DbType="Int")]
	public System.Nullable<int> Dc_Packing_List
	{
		get
		{
			return this._Dc_Packing_List;
		}
		set
		{
			if ((this._Dc_Packing_List != value))
			{
				this._Dc_Packing_List = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCL_No", DbType="NVarChar(50)")]
	public string DCL_No
	{
		get
		{
			return this._DCL_No;
		}
		set
		{
			if ((this._DCL_No != value))
			{
				this._DCL_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dc_Packing", DbType="Int")]
	public System.Nullable<int> Dc_Packing
	{
		get
		{
			return this._Dc_Packing;
		}
		set
		{
			if ((this._Dc_Packing != value))
			{
				this._Dc_Packing = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dc_No", DbType="NVarChar(50)")]
	public string Dc_No
	{
		get
		{
			return this._Dc_No;
		}
		set
		{
			if ((this._Dc_No != value))
			{
				this._Dc_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plant", DbType="NVarChar(10)")]
	public string Plant
	{
		get
		{
			return this._Plant;
		}
		set
		{
			if ((this._Plant != value))
			{
				this._Plant = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_By", DbType="VarChar(20)")]
	public string Created_By
	{
		get
		{
			return this._Created_By;
		}
		set
		{
			if ((this._Created_By != value))
			{
				this._Created_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Created_Date
	{
		get
		{
			return this._Created_Date;
		}
		set
		{
			if ((this._Created_Date != value))
			{
				this._Created_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_By", DbType="VarChar(20)")]
	public string Modified_By
	{
		get
		{
			return this._Modified_By;
		}
		set
		{
			if ((this._Modified_By != value))
			{
				this._Modified_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Modified_Date
	{
		get
		{
			return this._Modified_Date;
		}
		set
		{
			if ((this._Modified_Date != value))
			{
				this._Modified_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization_After", DbType="Int")]
	public System.Nullable<int> Sterilization_After
	{
		get
		{
			return this._Sterilization_After;
		}
		set
		{
			if ((this._Sterilization_After != value))
			{
				this._Sterilization_After = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization_No_After", DbType="NVarChar(50)")]
	public string Sterilization_No_After
	{
		get
		{
			return this._Sterilization_No_After;
		}
		set
		{
			if ((this._Sterilization_No_After != value))
			{
				this._Sterilization_No_After = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization_Reject", DbType="Int")]
	public System.Nullable<int> Sterilization_Reject
	{
		get
		{
			return this._Sterilization_Reject;
		}
		set
		{
			if ((this._Sterilization_Reject != value))
			{
				this._Sterilization_Reject = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty_1", DbType="Int")]
	public System.Nullable<int> Qty_1
	{
		get
		{
			return this._Qty_1;
		}
		set
		{
			if ((this._Qty_1 != value))
			{
				this._Qty_1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(25)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this._Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_Reject", DbType="Int")]
	public System.Nullable<int> Box_Reject
	{
		get
		{
			return this._Box_Reject;
		}
		set
		{
			if ((this._Box_Reject != value))
			{
				this._Box_Reject = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_Reject_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Box_Reject_Date
	{
		get
		{
			return this._Box_Reject_Date;
		}
		set
		{
			if ((this._Box_Reject_Date != value))
			{
				this._Box_Reject_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_Reject_By", DbType="NVarChar(20)")]
	public string Box_Reject_By
	{
		get
		{
			return this._Box_Reject_By;
		}
		set
		{
			if ((this._Box_Reject_By != value))
			{
				this._Box_Reject_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Sterilization_Date
	{
		get
		{
			return this._Sterilization_Date;
		}
		set
		{
			if ((this._Sterilization_Date != value))
			{
				this._Sterilization_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization_By", DbType="NVarChar(15)")]
	public string Sterilization_By
	{
		get
		{
			return this._Sterilization_By;
		}
		set
		{
			if ((this._Sterilization_By != value))
			{
				this._Sterilization_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_By", DbType="NVarChar(15)")]
	public string Box_By
	{
		get
		{
			return this._Box_By;
		}
		set
		{
			if ((this._Box_By != value))
			{
				this._Box_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_Date", DbType="NVarChar(15)")]
	public string Box_Date
	{
		get
		{
			return this._Box_Date;
		}
		set
		{
			if ((this._Box_Date != value))
			{
				this._Box_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Print_Name", DbType="NVarChar(50)")]
	public string Print_Name
	{
		get
		{
			return this._Print_Name;
		}
		set
		{
			if ((this._Print_Name != value))
			{
				this._Print_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Packing_Model", DbType="NVarChar(50)")]
	public string Packing_Model
	{
		get
		{
			return this._Packing_Model;
		}
		set
		{
			if ((this._Packing_Model != value))
			{
				this._Packing_Model = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ord_Country", DbType="NVarChar(50)")]
	public string Ord_Country
	{
		get
		{
			return this._Ord_Country;
		}
		set
		{
			if ((this._Ord_Country != value))
			{
				this._Ord_Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numoflens", DbType="Int")]
	public System.Nullable<int> numoflens
	{
		get
		{
			return this._numoflens;
		}
		set
		{
			if ((this._numoflens != value))
			{
				this._numoflens = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numofbigbox", DbType="Int")]
	public System.Nullable<int> numofbigbox
	{
		get
		{
			return this._numofbigbox;
		}
		set
		{
			if ((this._numofbigbox != value))
			{
				this._numofbigbox = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numofsbinbb", DbType="Int")]
	public System.Nullable<int> numofsbinbb
	{
		get
		{
			return this._numofsbinbb;
		}
		set
		{
			if ((this._numofsbinbb != value))
			{
				this._numofsbinbb = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scan", DbType="Int")]
	public System.Nullable<int> scan
	{
		get
		{
			return this._scan;
		}
		set
		{
			if ((this._scan != value))
			{
				this._scan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Small_box", DbType="Int")]
	public System.Nullable<int> Small_box
	{
		get
		{
			return this._Small_box;
		}
		set
		{
			if ((this._Small_box != value))
			{
				this._Small_box = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Big_box", DbType="Int")]
	public System.Nullable<int> Big_box
	{
		get
		{
			return this._Big_box;
		}
		set
		{
			if ((this._Big_box != value))
			{
				this._Big_box = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numofsbox", DbType="Int")]
	public System.Nullable<int> Numofsbox
	{
		get
		{
			return this._Numofsbox;
		}
		set
		{
			if ((this._Numofsbox != value))
			{
				this._Numofsbox = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Btc_No", DbType="VarChar(30)")]
	public string Btc_No
	{
		get
		{
			return this._Btc_No;
		}
		set
		{
			if ((this._Btc_No != value))
			{
				this._Btc_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="VarChar(30)")]
	public string price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterility_Comp_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Sterility_Comp_Date
	{
		get
		{
			return this._Sterility_Comp_Date;
		}
		set
		{
			if ((this._Sterility_Comp_Date != value))
			{
				this._Sterility_Comp_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sales_Ord_No", DbType="VarChar(50)")]
	public string Sales_Ord_No
	{
		get
		{
			return this._Sales_Ord_No;
		}
		set
		{
			if ((this._Sales_Ord_No != value))
			{
				this._Sales_Ord_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterility_Status", DbType="Int")]
	public System.Nullable<int> Sterility_Status
	{
		get
		{
			return this._Sterility_Status;
		}
		set
		{
			if ((this._Sterility_Status != value))
			{
				this._Sterility_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Injector_Ref", DbType="NVarChar(10)")]
	public string Injector_Ref
	{
		get
		{
			return this._Injector_Ref;
		}
		set
		{
			if ((this._Injector_Ref != value))
			{
				this._Injector_Ref = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Injector_batch", DbType="NVarChar(50)")]
	public string Injector_batch
	{
		get
		{
			return this._Injector_batch;
		}
		set
		{
			if ((this._Injector_batch != value))
			{
				this._Injector_batch = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Power", DbType="NVarChar(20)")]
	public string R_Power
	{
		get
		{
			return this._R_Power;
		}
		set
		{
			if ((this._R_Power != value))
			{
				this._R_Power = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cylsize", DbType="NVarChar(20)")]
	public string Cylsize
	{
		get
		{
			return this._Cylsize;
		}
		set
		{
			if ((this._Cylsize != value))
			{
				this._Cylsize = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rotlex_type", DbType="VarChar(50)")]
	public string rotlex_type
	{
		get
		{
			return this._rotlex_type;
		}
		set
		{
			if ((this._rotlex_type != value))
			{
				this._rotlex_type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Label", DbType="Int")]
	public System.Nullable<int> Label
	{
		get
		{
			return this._Label;
		}
		set
		{
			if ((this._Label != value))
			{
				this._Label = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefLot", DbType="VarChar(50)")]
	public string RefLot
	{
		get
		{
			return this._RefLot;
		}
		set
		{
			if ((this._RefLot != value))
			{
				this._RefLot = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTS_No", DbType="VarChar(50)")]
	public string MTS_No
	{
		get
		{
			return this._MTS_No;
		}
		set
		{
			if ((this._MTS_No != value))
			{
				this._MTS_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_No", DbType="NVarChar(MAX)")]
	public string Box_No
	{
		get
		{
			return this._Box_No;
		}
		set
		{
			if ((this._Box_No != value))
			{
				this._Box_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dc_Status", DbType="Int")]
	public System.Nullable<int> Dc_Status
	{
		get
		{
			return this._Dc_Status;
		}
		set
		{
			if ((this._Dc_Status != value))
			{
				this._Dc_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_code", DbType="NVarChar(50)")]
	public string Product_code
	{
		get
		{
			return this._Product_code;
		}
		set
		{
			if ((this._Product_code != value))
			{
				this._Product_code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PouchPrint", DbType="Int")]
	public System.Nullable<int> PouchPrint
	{
		get
		{
			return this._PouchPrint;
		}
		set
		{
			if ((this._PouchPrint != value))
			{
				this._PouchPrint = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowerPrint", DbType="Int")]
	public System.Nullable<int> PowerPrint
	{
		get
		{
			return this._PowerPrint;
		}
		set
		{
			if ((this._PowerPrint != value))
			{
				this._PowerPrint = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Export_Qty", DbType="Int")]
	public System.Nullable<int> Export_Qty
	{
		get
		{
			return this._Export_Qty;
		}
		set
		{
			if ((this._Export_Qty != value))
			{
				this._Export_Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this._Location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inward_No", DbType="Int")]
	public System.Nullable<int> Inward_No
	{
		get
		{
			return this._Inward_No;
		}
		set
		{
			if ((this._Inward_No != value))
			{
				this._Inward_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inward_No1", DbType="VarChar(50)")]
	public string Inward_No1
	{
		get
		{
			return this._Inward_No1;
		}
		set
		{
			if ((this._Inward_No1 != value))
			{
				this._Inward_No1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inward_Date", DbType="Date")]
	public System.Nullable<System.DateTime> Inward_Date
	{
		get
		{
			return this._Inward_Date;
		}
		set
		{
			if ((this._Inward_Date != value))
			{
				this._Inward_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box_Type", DbType="VarChar(50)")]
	public string Box_Type
	{
		get
		{
			return this._Box_Type;
		}
		set
		{
			if ((this._Box_Type != value))
			{
				this._Box_Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boxtime", DbType="DateTime")]
	public System.Nullable<System.DateTime> Boxtime
	{
		get
		{
			return this._Boxtime;
		}
		set
		{
			if ((this._Boxtime != value))
			{
				this._Boxtime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PouchStation", DbType="VarChar(50)")]
	public string PouchStation
	{
		get
		{
			return this._PouchStation;
		}
		set
		{
			if ((this._PouchStation != value))
			{
				this._PouchStation = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Station", DbType="VarChar(50)")]
	public string Station
	{
		get
		{
			return this._Station;
		}
		set
		{
			if ((this._Station != value))
			{
				this._Station = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PouchBTWLabelName", DbType="VarChar(50)")]
	public string PouchBTWLabelName
	{
		get
		{
			return this._PouchBTWLabelName;
		}
		set
		{
			if ((this._PouchBTWLabelName != value))
			{
				this._PouchBTWLabelName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tray_Label_Gen", DbType="Int")]
	public System.Nullable<int> Tray_Label_Gen
	{
		get
		{
			return this._Tray_Label_Gen;
		}
		set
		{
			if ((this._Tray_Label_Gen != value))
			{
				this._Tray_Label_Gen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tray_No", DbType="VarChar(50)")]
	public string Tray_No
	{
		get
		{
			return this._Tray_No;
		}
		set
		{
			if ((this._Tray_No != value))
			{
				this._Tray_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Udi_code", DbType="NVarChar(100)")]
	public string Udi_code
	{
		get
		{
			return this._Udi_code;
		}
		set
		{
			if ((this._Udi_code != value))
			{
				this._Udi_code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Injector_Lot", DbType="NVarChar(50)")]
	public string Injector_Lot
	{
		get
		{
			return this._Injector_Lot;
		}
		set
		{
			if ((this._Injector_Lot != value))
			{
				this._Injector_Lot = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rack_Location", DbType="NVarChar(50)")]
	public string Rack_Location
	{
		get
		{
			return this._Rack_Location;
		}
		set
		{
			if ((this._Rack_Location != value))
			{
				this._Rack_Location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pouchRepack_staus", DbType="Int")]
	public System.Nullable<int> pouchRepack_staus
	{
		get
		{
			return this._pouchRepack_staus;
		}
		set
		{
			if ((this._pouchRepack_staus != value))
			{
				this._pouchRepack_staus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPL_Collection_Status", DbType="Int")]
	public System.Nullable<int> BPL_Collection_Status
	{
		get
		{
			return this._BPL_Collection_Status;
		}
		set
		{
			if ((this._BPL_Collection_Status != value))
			{
				this._BPL_Collection_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bpl_cancel_status", DbType="Int")]
	public System.Nullable<int> bpl_cancel_status
	{
		get
		{
			return this._bpl_cancel_status;
		}
		set
		{
			if ((this._bpl_cancel_status != value))
			{
				this._bpl_cancel_status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPL_Collected_by", DbType="NVarChar(50)")]
	public string BPL_Collected_by
	{
		get
		{
			return this._BPL_Collected_by;
		}
		set
		{
			if ((this._BPL_Collected_by != value))
			{
				this._BPL_Collected_by = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Repk_Scanned", DbType="Int")]
	public System.Nullable<int> Repk_Scanned
	{
		get
		{
			return this._Repk_Scanned;
		}
		set
		{
			if ((this._Repk_Scanned != value))
			{
				this._Repk_Scanned = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Areation_Status", DbType="Int")]
	public System.Nullable<int> Areation_Status
	{
		get
		{
			return this._Areation_Status;
		}
		set
		{
			if ((this._Areation_Status != value))
			{
				this._Areation_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Areation_scan", DbType="Int")]
	public System.Nullable<int> Areation_scan
	{
		get
		{
			return this._Areation_scan;
		}
		set
		{
			if ((this._Areation_scan != value))
			{
				this._Areation_scan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterilization_scan", DbType="Int")]
	public System.Nullable<int> Sterilization_scan
	{
		get
		{
			return this._Sterilization_scan;
		}
		set
		{
			if ((this._Sterilization_scan != value))
			{
				this._Sterilization_scan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pouch_Order_Type", DbType="VarChar(50)")]
	public string Pouch_Order_Type
	{
		get
		{
			return this._Pouch_Order_Type;
		}
		set
		{
			if ((this._Pouch_Order_Type != value))
			{
				this._Pouch_Order_Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pouch_Order_Country", DbType="VarChar(50)")]
	public string Pouch_Order_Country
	{
		get
		{
			return this._Pouch_Order_Country;
		}
		set
		{
			if ((this._Pouch_Order_Country != value))
			{
				this._Pouch_Order_Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Areation_Scan_No", DbType="NVarChar(50)")]
	public string Areation_Scan_No
	{
		get
		{
			return this._Areation_Scan_No;
		}
		set
		{
			if ((this._Areation_Scan_No != value))
			{
				this._Areation_Scan_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterile_to_Areation_Move_status", DbType="Int")]
	public System.Nullable<int> Sterile_to_Areation_Move_status
	{
		get
		{
			return this._Sterile_to_Areation_Move_status;
		}
		set
		{
			if ((this._Sterile_to_Areation_Move_status != value))
			{
				this._Sterile_to_Areation_Move_status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterile_to_Areation_Move_NO", DbType="VarChar(50)")]
	public string Sterile_to_Areation_Move_NO
	{
		get
		{
			return this._Sterile_to_Areation_Move_NO;
		}
		set
		{
			if ((this._Sterile_to_Areation_Move_NO != value))
			{
				this._Sterile_to_Areation_Move_NO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoxBTWLabelName", DbType="VarChar(50)")]
	public string BoxBTWLabelName
	{
		get
		{
			return this._BoxBTWLabelName;
		}
		set
		{
			if ((this._BoxBTWLabelName != value))
			{
				this._BoxBTWLabelName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShrinkWarp_Rejection", DbType="Int")]
	public System.Nullable<int> ShrinkWarp_Rejection
	{
		get
		{
			return this._ShrinkWarp_Rejection;
		}
		set
		{
			if ((this._ShrinkWarp_Rejection != value))
			{
				this._ShrinkWarp_Rejection = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShrinkWarp_Rejection_Move_No", DbType="VarChar(50)")]
	public string ShrinkWarp_Rejection_Move_No
	{
		get
		{
			return this._ShrinkWarp_Rejection_Move_No;
		}
		set
		{
			if ((this._ShrinkWarp_Rejection_Move_No != value))
			{
				this._ShrinkWarp_Rejection_Move_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PouchPack_to_Sterile_Move_status", DbType="Int")]
	public System.Nullable<int> PouchPack_to_Sterile_Move_status
	{
		get
		{
			return this._PouchPack_to_Sterile_Move_status;
		}
		set
		{
			if ((this._PouchPack_to_Sterile_Move_status != value))
			{
				this._PouchPack_to_Sterile_Move_status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PouchPack_to_Sterile_Move_No", DbType="VarChar(50)")]
	public string PouchPack_to_Sterile_Move_No
	{
		get
		{
			return this._PouchPack_to_Sterile_Move_No;
		}
		set
		{
			if ((this._PouchPack_to_Sterile_Move_No != value))
			{
				this._PouchPack_to_Sterile_Move_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tray_Allot_No", DbType="VarChar(50)")]
	public string Tray_Allot_No
	{
		get
		{
			return this._Tray_Allot_No;
		}
		set
		{
			if ((this._Tray_Allot_No != value))
			{
				this._Tray_Allot_No = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lens_Reserved_status", DbType="Int")]
	public System.Nullable<int> Lens_Reserved_status
	{
		get
		{
			return this._Lens_Reserved_status;
		}
		set
		{
			if ((this._Lens_Reserved_status != value))
			{
				this._Lens_Reserved_status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserved_Id", DbType="NVarChar(50)")]
	public string Reserved_Id
	{
		get
		{
			return this._Reserved_Id;
		}
		set
		{
			if ((this._Reserved_Id != value))
			{
				this._Reserved_Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BI_Start_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> BI_Start_Date
	{
		get
		{
			return this._BI_Start_Date;
		}
		set
		{
			if ((this._BI_Start_Date != value))
			{
				this._BI_Start_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BI_End_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> BI_End_Date
	{
		get
		{
			return this._BI_End_Date;
		}
		set
		{
			if ((this._BI_End_Date != value))
			{
				this._BI_End_Date = value;
			}
		}
	}
}
#pragma warning restore 1591
